
var mongoose = require('mongoose');  
var Schema = mongoose.Schema;  
var companiesSchema = new Schema({      
    id: { type: name   },       
    acquisition: { 
        acquired_day :{type:String},
        acquired_month : {type: String},
        acuired_year : {type:String},
        //acquired
        price_amount : {type: int},
        price_currency : {type:String},
        source_description : {type:String},
        source_url : {type:String},
        term_code:{type : String},
          },     
    acquisitions: { type: Array},       
    alias_list: { type: String}, 
    blog_feed_url: { type : String },
    category_code : { type :String },
    competitions : { type: String },
    created_at : { type : String },
    crunchbase_url : { type : String },
    deadpooled_day : { type : String },
    deadpooled_month : { type : String },
    deadpooled_url : { type : String },
    deadpooled_year : { type : String },
    description : { type : String },
    email_address : { type : String },
    external_links : { type : Array },
    founded_day : {type : String },
    founded_month : { type: String },
    founded_year : {type : String},
    founded_rounds : { type: Array},
    homepage_url : {type: String},
    investments : {type : Array},
    ipo : {
        pub_day : {type: String},
        pub_month : {type:String},
        pub_year : {type:String},
        stock_symbol :{type:String},
        valuation_amount : {type:String},
        valuation_currency : {ype: String},
    },
    milestones : {type: Array},
    name : {type: String},
    number_of_employees : {type : int},
    offices : {type: Array},
    overview : {type:String},
    partners : {type : Array},
    permalink : {type:String},
    phone_number : {type : String},
    products : {type : Array},
    providerships : {type : Array},
    relationships : {type: Array},
    tag_list : {type : String},
    total_money_raised : {type : String},
    twitter_username : {type : String},
    updtated_at: {type :String},
    video_embeds : {type :Array},
},{ versionKey: false });  

const Companies = module.exports = mongoose.model('Companies', companiesSchema)