
var mongoose = require('mongoose');  
//var Schema = mongoose.Schema;  
var companies= mongoose.Schema({      
    id: { type: mongoose.Schema.Types.ObjectId },       
    acquisition: { 
        acquired_day : String,
        acquired_month : String,
        acuired_year : String,
        price_amount : Number,
        acquiring_companies: {type: mongoose.Schema.Types.Mixed},
        price_currency : String,
        source_description : String,
        source_url : String,
        term_code: String,
          },     
    acquisitions: [mongoose.Schema.Types.Mixed],       
    alias_list: String, 
    blog_feed_url: String,
    category_code : String,
    competitions : [mongoose.Schema.Types.Mixed],
    created_at : String,
    crunchbase_url : String,
    deadpooled_day : String,
    deadpooled_month : String,
    deadpooled_url : String,
    deadpooled_year : String,
    description : String,
    email_address : String,
    external_links : Array,
    founded_day : String,
    founded_month : String,
    founded_year : String,
    founded_rounds : [mongoose.Schema.Types.Mixed],
    homepage_url : String,
    investments : [mongoose.Schema.Types.Mixed],
    ipo : {
        pub_day : String,
        pub_month : String,
        pub_year : String,
        stock_symbol :String,
        valuation_amount : String,
        valuation_currency : String,
    },
    milestones : [mongoose.Schema.Types.Mixed],
    name : String,
    number_of_employees : Number,
    offices : [mongoose.Schema.Types.Mixed],
    overview : String,
    partners : [mongoose.Schema.Types.Mixed],
    permalink : String,
    phone_number : String,
    products : [mongoose.Schema.Types.Mixed],
    providerships : [mongoose.Schema.Types.Mixed],
    relationships : [mongoose.Schema.Types.Mixed],
    tag_list : String,
    total_money_raised : String,
    twitter_username : String,
    updtated_at: String,
    video_embeds : [mongoose.Schema.Types.Mixed],
},{ versionKey: false });  

const Companies = module.exports = mongoose.model('Companies', companies); 